version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEVICE=cpu # Change to cuda if you have GPU support
      - BACKEND=onnxruntime
      - POSE_MODE=performance
      - USE_REDIS=true
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./app:/app/app
      - ./physiotrack_core:/app/physiotrack_core
    depends_on:
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
